"""add report_history audit trail

Revision ID: 0874f3834540
Revises: f9f56f9520eb
Create Date: 2026-08-14 13:44:21.193386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0874f3834540'
down_revision: Union[str, None] = 'f9f56f9520eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.SmallInteger(), nullable=False),
    sa.Column('action', sa.Unicode(length=20), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('old_values', sa.UnicodeText(), nullable=True),
    sa.Column('new_values', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_history_line_id'), 'report_history', ['line_id'], unique=False)
    op.create_index(op.f('ix_report_history_report_date'), 'report_history', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_history_report_date'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_line_id'), table_name='report_history')
    op.drop_table('report_history')
    # ### end Alembic commands ###
