"""initial schema

Revision ID: 55bf28879b27
Revises: 
Create Date: 2026-08-12 22:05:34.141393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55bf28879b27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('to_truong', 'thu_ky', 'sep', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.String(length=20), nullable=False),
    sa.Column('executive_name', sa.String(length=100), nullable=False),
    sa.Column('pu_group', sa.Enum('PU1', 'PU2', name='pugroup'), nullable=False),
    sa.Column('buyer', sa.String(length=100), nullable=False),
    sa.Column('sam', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_output', sa.Integer(), nullable=False),
    sa.Column('target_eff', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('to_truong_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['to_truong_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_number')
    )
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.SmallInteger(), nullable=False),
    sa.Column('out_sew', sa.Integer(), nullable=True),
    sa.Column('eff_sew', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('out_fin_scanpack', sa.Integer(), nullable=True),
    sa.Column('out_fin_fin', sa.Integer(), nullable=True),
    sa.Column('eff_fin', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wip_fin', sa.Integer(), nullable=True),
    sa.Column('issue_note', sa.Text(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('secretary_override', sa.Boolean(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id', 'report_date', 'shift', name='uq_line_date_shift')
    )
    op.create_index(op.f('ix_daily_reports_report_date'), 'daily_reports', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_reports_report_date'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_table('lines')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
