"""add executive role and executive_name to users

Revision ID: ab079b4d041b
Revises: 0f83202e5ab8
Create Date: 2026-08-17 09:22:58.786864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ab079b4d041b'
down_revision: Union[str, None] = '0f83202e5ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('executive_name', sa.Unicode(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'executive_name')
    # ### end Alembic commands ###
