"""daily sam and target on reports

Revision ID: c1d3a24fc56c
Revises: 640115054138
Create Date: 2026-08-14 10:01:56.632799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c1d3a24fc56c'
down_revision: Union[str, None] = '640115054138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reports', sa.Column('sam', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('daily_reports', sa.Column('target_output', sa.Integer(), nullable=True))
    op.add_column('daily_reports', sa.Column('target_eff', sa.Numeric(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_reports', 'target_eff')
    op.drop_column('daily_reports', 'target_output')
    op.drop_column('daily_reports', 'sam')
    # ### end Alembic commands ###
