"""replace wip_fin with wip_dip and wip_pre_pi

Revision ID: f9f56f9520eb
Revises: c1d3a24fc56c
Create Date: 2026-08-14 10:44:38.877510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f9f56f9520eb'
down_revision: Union[str, None] = 'c1d3a24fc56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reports', sa.Column('wip_dip', sa.Integer(), nullable=True))
    op.add_column('daily_reports', sa.Column('wip_pre_pi', sa.Integer(), nullable=True))
    op.drop_column('daily_reports', 'wip_fin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reports', sa.Column('wip_fin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('daily_reports', 'wip_pre_pi')
    op.drop_column('daily_reports', 'wip_dip')
    # ### end Alembic commands ###
